spring:
  kafka:
    bootstrap-servers: kafka:9092
  
  datasource:
    url: jdbc:h2:mem:messagedb

app:
  kafka:
    input-topic: input-messages
    output-topic: output-messages
    consumer-group: message-processor-group

logging:
  level:
    com.zetta.task: INFO
